config/routes.rb
AeoBruins::Application.routes.draw do

  get "home/index"
  resources :contacts, :only => [:new, :create]
  resources :brothers

  root 'home#index'

  get 'about' => 'about#show'

  

end

app/models/brother.rb
class Brother < ActiveRecord::Base
  attr_accessible :name, :major, :biography, :avatar
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible  :first_name, :last_name, :subject, :message, :email
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :subject, presence: true
  validates_format_of :email, presence: true, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  validates :message, presence: true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def show
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/brothers_controller.rb
class BrothersController < ApplicationController
  before_action :set_brother, only: [:show, :edit, :update, :destroy]

  # GET /brothers
  # GET /brothers.json
  def index
    @brothers = Brother.all
  end

  # GET /brothers/1
  # GET /brothers/1.json
  def show
  end

  # GET /brothers/new
  def new
    @brother = Brother.new
  end

  # GET /brothers/1/edit
  def edit
  end

  # POST /brothers
  # POST /brothers.json
  def create
    @brother = Brother.new(brother_params)

    respond_to do |format|
      if @brother.save
        format.html { redirect_to @brother, notice: 'Brother was successfully created.' }
        format.json { render action: 'show', status: :created, location: @brother }
      else
        format.html { render action: 'new' }
        format.json { render json: @brother.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /brothers/1
  # PATCH/PUT /brothers/1.json
  def update
    respond_to do |format|
      if @brother.update(brother_params)
        format.html { redirect_to @brother, notice: 'Brother was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @brother.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brothers/1
  # DELETE /brothers/1.json
  def destroy
    @brother.destroy
    respond_to do |format|
      format.html { redirect_to brothers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brother
      @brother = Brother.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brother_params
      params.require(:brother).permit(:name, :major, :biography, :avatar)
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        # Send an email only when in production.
        ContactMailer.contact_email(@contact).deliver if Rails.env.production?

        format.html { redirect_to '/', notice: 'Contact was successfully created.' }
        format.json { render json: 'Contact Created', status: created }
      else
        format.html { render action: 'new' }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:first_name, :last_name, :email, :subject, :message)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brothers_helper.rb
module BrothersHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/about/show.html.erb
<div class='row'>
  <div class="about span10 center-me">
    <div class='content span9 center-me'>
      <h2>Our Mission</h2>
      <p>The goal of Alpha Epsilon Omega at University of California in Los Angeles is to create an environment where
        bonds are made and strengthened between its members. Ultimately these bonds are to serve as powerful networking
        tools during and beyond our college years. Alpha Epsilon Omega promotes the Armenian history,
        language and culture on campus by hosting a variety of events and extending membership to men from all ethnic
        backgrounds. Our organization leadership experience by placing members in leadership positions. Alpha Epsilon
        Omega will support its members in reaching the highest standards of achievement in all aspects of their lives.
      </p>
      <p>These men felt that although the competitive UCLA environment demanded a lot from a student,
        especially from those who were interested in education beyond their undergraduate work,
        there was still a place for an organization such as Alpha Epsilon Omega to make their college experience
        truly memorable.</p>

      <h2>Beta Chapter at UCLA</h2>
      <p>The Beta chapter of Alpha Epsilon Omega was started at UCLA on May 9, 2001 becoming one of more thatn 60
        Greek letter-organizations on campus. The founding members were Arthur Jordan, Aris Minas, Arbi Nazarian,
        Manuel Avedissian, Tevan Ovsepyan, and Nerses Kazaryan. These founders were a group of men who cam from a
        variety of Amrniean backgrounds and academic majors. </p>

      <h2>National History</h2>
      <p>Alpha Epsilon Omega was established on December 20, 2000 by Hakop Sinoryan, Misak Zetilyan,
        and Antranik Satamian at California State University, Northridge. During a High School Exchange trip to Armenia in
        the spring of 1999, these men saw an impoverished nation with wide spread corruption and injustice. Upon returning
        to the United States, their experiences in Armenia and a passion for their Armenian heritage inspired them to
        establish an after-school program for the Armenian youth in their hometown of Pasadena, California. As freshmen in
        college, their studies and work created time constraints forcing the triumvirate to abandon the after-school
        program in the fall of 1999, still in the planning stages. The notion of &#8220;unity for the advancement of the
        Armenian nation&#8221; was still living in the minds of the Triumvirate. At the completion of the spring 2000
        semester the Triumvirate convened to reignite the mission of creating a social, cultural, and philanthropic
        organization for the advancement of the Armenian nation. They agreed on the establishment of a lifelong fraternal
        society which would serve as a catalyst in executing the principles set forth by the Triumvirate.</p>

      <p>Throughout the following six months the Triumvirate would set the foundation of Alpha Epsilon Omega, and recruit
        gentlemen to establish the fraternity at California State University, Northridge. The fraternity chartered its
        first chapter, Alpha Chapter, at California State University Northridge in the spring of 2001. Two months after
        chartering the Alpha Chapter, the organization was successful in chartering the Beta Chapter at the University of
        California, Los Angeles. For one year the fraternity grew in numbers and became active in their respective
        universities. In the summer of 2002 the Gamma Chapter was chartered at the University of California, Irvine. Fall
        2003 saw the inclusion of yet another chapter in Alpha Epsilon Omega; the Delta Chapter was chartered at
        California State University, Los Angeles. During the next two years Alpha Epsilon Omega would grow exponentially
        in numbers, exceeding one hundred brothers. Qualitative growth contributed to the development of Alpha Epsilon
        Omega. By recruiting members based on the notion &#8220;quality over quantity&#8221;, the fraternity became
        successful in the undertaking of various cultural and philanthropic endeavors. A number of which continue to this
        day. In the fall of 2004, group of gentlemen at the University of Southern California, and California State
        University, Pomona approached the fraternity with the intention of establishing a chapter at their respective
        universities. Their goal was realized when the fraternity chartered the Epsilon Chapter at the University of
        Southern California in the summer of 2005. In the fall of 2006, Alpha Epsilon Omega expanded its reach south of
        Orange County and into San Diego. The fraternity chartered its seventh chapter, the Eta Chapter, at the University
        of California, San Diego. Brotherhood is a key element in Alpha Epsilon Omega. It is the backbone of the
        organization, binding every member together.</p>

      <a name='academics'></a>
      <h2>Our Brotherhood</h2>
      <p>Brotherhood is a key element at Alpha Epsilon Omega, where life-long friendships are made. Sharing good times
        with your fraternity brothers is an experience that can&#8217;t be matched. By being a member of Alpha Epsilon
        Omega you will enhance your college experience and make them the best years of your life.</p>

      <h2>Academics</h2>
      <p>At Alpha Epsilon Omega we never forget that we are students first. We hold academic achievement above all else.
        As a member you will find that your brothers are often your most valuable academic resource. In addition we also
        provide resources to our members who would like to learn more about Armenian history, language, and culture.</p>

      <a name='philanthropy'></a>
      <h2>Philanthropy</h2>
      <p>Alpha Epsilon Omega is always looking to help out Armenians both here and in Armenia. Alpha Epsilon Omega
        regularly participates in various philanthropic activities benefiting the Armenian Community and advances The
        Armenian Cause.</p>
      <p>
        One of the cornerstones of our organization is the philanthropic work we do to better the Armenian Community.
        Our primary philanthropic project is the Armenian Educational Relief Fund (AERF) which was started in 2006 by
        the brothers of Alpha Epsilon Omega. The goal of AERF is to provide essential school supplies to schoolchildren
        in the outskirts of Armenia. AERF also focuses on renovating kindergartens that are in need of repairs to
        provide a safe learning environment for students.
      </p>
      <p>
        So far, we have made four trips to various Armenian cities including Ashtarak, Armavir, Stenapavan, and Hrazdan.
        In total, AERF has helped 9 kindergartens housing over 700 students by donating backpacks filled with school
        supplies, writing materials, playground play-sets, chairs, and many other essential school supplies and repairs.
        We continue our efforts to improve the educational experience of children in Armenia. We are currently
        fundraising for Project Number Five which has a goal of donating 1000 backpacks through the summer of 2014.
      </p>

      <h2>Pledgeship</h2>
      <p>At Alpha Epsilon Omega, we have only two objectives for our pledges, to learn about the traditions of our
        fraternity and to have fun. Most brothers fondly remember their pledge term as their most exciting semester of
        college. During your pledgeship, you will establish life-long friendships, have unforgettable experiences, and
        embrace the virtues of your new fraternity.</p>

      <a name='sports'></a>
      <h2>Sports</h2>
      <p>At Alpha Epsilon Omega, we regularly participate in sporting events both at school and in the community. We
        participate in Intramural tournaments on campus, competing against other fraternities and clubs.</p>

      <h2>Why Rush?</h2>
      <p>Joining Alpha Epsilon Omega will make your college experience one to remember. Brotherhood, academics,
        philanthropy, social life, fun and most importantly being Armenian are facets of being a member of Alpha
        Epsilon Omega.</p>

      <h2>How to Rush?</h2>
      <p>We hold rush at the beginning of each term, at this time you will see our flyers and billboards on campus. The
        best way to rush is to ask the brothers, who will be wearing t-shirts and sweatshirts with the letters of AEO, for
        information on rush events. If you have any questions or would like to rush please
        <%= link_to "contact us", new_contact_path %>.</p>
    </div>

  </div>
  <div class='about-content-bottom'></div>
</div>

app/views/brothers/_details.html.erb
<div class="row brother-details">
  <div class='span3'>
    <%= image_tag brother.avatar.url(:medium), :alt=>brother.name %>
  </div>
  <div class='span6'>
    <h3><%=brother.name %></h3>

    <h4><%=brother.major %></h4>

    <p><%=brother.biography %></p>

    <%= link_to 'Edit', edit_brother_path(brother) %>
  </div>
</div>

app/views/brothers/_form.html.erb
<% if @brother.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@brother.errors.count, "error") %> prohibited this brother from being saved:</h2>

    <ul>
      <% @brother.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>


<%= form_for(@brother, :html => { :multipart => true, :class=>"well span8 center-me brother-form" }) do |f| %>
  <div class="row">

    <div class="span3">
      <%= f.label :name %>
      <%= f.text_field :name, :class=>'span3', :placeholder=>'Your Name' %>
      <%= f.label :major %>
      <%= f.text_field :major, :class=>'span3', :placeholder=>'Your Major' %>
      <%= f.label :avatar %>
      <%= f.file_field :avatar %>
    </div>

    <div class="span5">
      <%= f.label :biography %>
      <%= f.text_area :biography, :class=>'input-xlarge span5', :rows=>10%>
    </div>

    <%= f.submit :value=>'Publish', :class=>'btn btn-primary pull-right'%>
    <%= link_to 'Cancel',brothers_path, :class=>'btn btn-primary pull-right'%>

  </div>
<% end %>

app/views/brothers/edit.html.erb
<%= render 'form' %>

app/views/brothers/index.html.erb
<div class='row'>
  <div class='span9 center-me'>
      <% @brothers.each do |brother| %>
        <%= render :partial => "details", :locals => {:brother => brother} %>
        <br />
      <% end %>
  </div>
</div>

<div class='row'>
  <div class='span2 center-me'>
    <%= link_to 'New Brother', new_brother_path %>
  </div>
</div>

app/views/brothers/new.html.erb
<%= render 'form' %>

app/views/brothers/show.html.erb
<div class='row'>
  <div class='span9 center-me'>
    <%= render :partial => "details", :locals => {:brother => @brother} %>
  </div>
</div>

app/views/contacts/_form.html.erb
<% if @contact.errors.any? %>
  <% @contact.errors.full_messages.each do |msg| %>
    <div class='alert alert-error'><%= msg %></div>
  <% end %>
<% end %>

<%= form_for(@contact, :html => {:class=>"well span8 center-me"}) do |f| %>
  <div class="row">

    <div class="span3">
      <%= f.label :first_name %>
      <%= f.text_field :first_name, :class=>'span3', :placeholder=>'Your First Name' %>
      <%= f.label :last_name %>
      <%= f.text_field :last_name, :class=>'span3', :placeholder=>'Your Last Name' %>
      <%= f.label :email %>
      <%= f.text_field :email, :class=>'span3', :placeholder=>'Your email address' %>
      <%= f.label :subject %>
      <%= f.select :subject, ['How do I rush?', 'General Information', 'Suggestions'] %>
    </div>

    <div class="span5">
      <%= f.label :message %>
      <%= f.text_area :message, :class=>'input-xlarge span5', :rows=>10%>
    </div>

    <%= f.submit :value=>'Send', :class=>'btn btn-primary pull-right'%>
  </div>
<% end %>

app/views/contacts/new.html.erb
<div class='row'>
  <%= render 'form' %>
</div>

app/views/home/index.html.erb
<!-- Carousel
================================================== -->
<div id="myCarousel" class="carousel slide">
  <div class="carousel-inner">

    <div class="item active">
      <%= image_tag "home/carousel/ucla-bruin-bear-dark.jpg"%>
      <div class="container">
        <div class="carousel-caption">
          <h1>The Armenian Fraternity.</h1>
          <p class="lead">Alpha Epsilon Omega is the only Armenian Fraternity on Campus. Established in 2000,
            the Beta chapter has a large network of alumni specialized in various fields.</p>
          <%= link_to "Sign up today", new_contact_path, :class=>'btn btn-large btn-primary'%>
        </div>
      </div>
    </div>

    <div class="item">
      <%= image_tag "home/carousel/ucla-campus-dark.jpg"%>
      <div class="container">
        <div class="carousel-caption">
          <h1>Strive for Perfection.</h1>
          <p class="lead">Our members are among the top students at UCLA. The Fraternity upholds high standards of
            achievement in all aspects of life. </p>
          <%= link_to "Sign up today", new_contact_path, :class=>'btn btn-large btn-primary'%>
        </div>
      </div>
    </div>

  </div>
  <a class="left carousel-control" href="#myCarousel" data-slide="prev">&lsaquo;</a>
  <a class="right carousel-control" href="#myCarousel" data-slide="next">&rsaquo;</a>
</div><!-- /.carousel -->

<hr class="featurette-divider">

<!-- Marketing messages.
================================================== -->
<!-- Wrap the rest of the page in another container to center all the content. -->

<div class="container marketing">

  <!-- Three columns of text below the carousel -->
  <div class="row">
    <div class="span4">
      <%= image_tag "home/marketing/academics.jpg" %>
      <h2>Academics</h2>
      <p>At Alpha Epsilon Omega we never forget that we are students first. We hold academic achievement above all else.
        As a member you will find that your brothers are often your most valuable academic resource. In addition we also
        provide resources to our members who would like to learn more about Armenian history, language, and culture.
      </p>
      <p><a class="btn" href="/about/#academics">View details &raquo;</a></p>
    </div><!-- /.span4 -->
    <div class="span4">
      <%= image_tag "home/marketing/sports.jpg" %>
      <h2>Sports</h2>
      <p>At Alpha Epsilon Omega, we regularly participate in sporting events both at school and in the community. We
        participate in Intramural tournaments on campus, competing against other fraternities and clubs.
      </p>
      <p><a class="btn" href="/about/#sports">View details &raquo;</a></p>
    </div><!-- /.span4 -->
    <div class="span4">
      <%= image_tag "home/marketing/philanthropy.jpg" %>
      <h2>Philanthropy</h2>
      <p>Alpha Epsilon Omega is always looking to help out Armenians both here and in Armenia. Alpha Epsilon Omega
        regularly participates in various philanthropic activities benefiting the Armenian Community and advances The
        Armenian Cause.
      </p>
      <p>
        <a class="btn" href="/about/#philanthropy">View details &raquo;</a></p>
    </div><!-- /.span4 -->
  </div><!-- /.row -->

</div>

<hr class="home-divider">

<div class="row">
  <div class="span6">
    <h2 class="promo-heading">Alpha Epsilon Omega at UCLA. <span class="muted">It'll blow your mind.</span></h2>
    <p class="lead">Whether you are a Freshman, Junior transfer, or a super-senior joining Alpha Epsilon Omega will be
      one of the best experiences of your college career. Feel free to reach out to us, come to our rush events,
      or just stop by for a friendly game of backgammon.</p>
  </div>
  <div class="span6">
    <div class="flex-video widescreen"><iframe src="//www.youtube.com/embed/XNradw0x4ZY" frameborder="0" allowfullscreen=""></iframe></div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<!-- FOOTER -->
<footer>
  <p class="pull-right"><a href="#">Back to top</a></p>
  <p class='copyright-text'>&copy; 2013 Alpha Epsilon Omega, Inc.</p>
</footer>

app/views/layouts/_header.html.erb
<head>
  <title>AEO Bruins</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= analytics_init if Rails.env.production? %>
  <%= csrf_meta_tags %>
</head>

app/views/layouts/_navigation.html.erb
<div class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <%= link_to " #{image_tag('flag.png')} UCLA | Alpha Epsilon Omega".html_safe, root_path, {:class => 'brand'} %>
      <div class="nav-collapse">
        <ul class="nav pull-right">
          <li class="<%= 'active' if params[:controller] == 'home' %>">
            <%= link_to :root do %>
              <i class="icon-home icon-white"></i> Home
            <% end %>
          </li>
          <li class="<%= 'active' if params[:controller] == 'about' %>"><%= link_to "Our History", :about%></li>
          <li class="<%= 'active' if params[:controller] == 'brothers' %>"><%= link_to "Meet the Brothers",
                                                                                       :brothers %></li>
          <li class="<%= 'active' if params[:controller] == 'contacts' %>"><%= link_to "Contact Us", :new_contact %></li>
        </ul>
      </div><!-- /.nav-collapse -->
    </div><!-- /.container -->
  </div><!-- /.navbar-inner -->
</div><!-- /.navbar -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <%= render 'layouts/header' %>
  <body>
    <%= render 'layouts/navigation' %>
    <div class="container">
      <%= yield %>
      <hr />
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>